/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    'Empty Spot': '空槽',
    'points': '点数',
    'Reset for +': '重置获得 +',
    'work': '工作',
    'More Mergeables': '更多可合并块',
    'Sell One': '出售1个',
    'Better Mergeables': '更好的合并块',
    'Cheaper Gilded Mergeables': '更便宜的镀金可合并块',
    'Faster Auto-Merge': '更快的自动合并',
    'first': '第一个',
    'Levels': '等级',
    'merge levels': '合并等级',
    'merge tokens': '合并令牌',
    'More Gilded Points': '更多镀金点',
    'More Merge Tokens': '更多合并令牌',
    'More Points': '更多点数',
    'Tokens': '令牌',
    'Unlock Auto-Buyer. Auto-Buyer will automatically buy any empty Mergeable slots.': '解锁自动购买器。 自动购买器 将自动购买任何空的 可合并 插槽。',
    'Unlock Auto-Merge. Auto-Merge will automatically merge all viable Mergeables once every 0.02s.': '解锁自动合并。 自动合并 将每 0.02 秒自动合并所有可用的 可合并块。',
    'Unlock automatic Gilded Auto-Merger. It runs every 0.38s.': '解锁自动镀金自动合并。 它每 0.38 秒运行一次。',
    'Unlock automatic Gilded Mergeables Auto-Buyer.': '解锁自动镀金合并自动购买器。',
    'Unlock automatic Gilded Upgrades buyer.': '解锁自动镀金升级购买器。',
    'Unlock automatic Merge Upgrades buyer.': '解锁自动合并升级购买器。',
    'Unlock Gilded Mergeables.': '解锁镀金可合并块。',
    'Unlock Gilded Points.': '解锁镀金点。',
    'Unlock Merge Mastery.': '解锁合并精通。',
    'Unlock Powers.': '解锁力量。',
    'Unlock Treasures.': '解锁宝藏。',
    'Unlock two Gilded Upgrades.': '解锁两个镀金升级。',
    'Unlock two upgrades.': '解锁两个升级。',
    'You passively gain 25% of potential gilded points each second.': '你每秒被动地获得 25% 的潜在镀金点数。',
    'You passively gain 25% of potential work each second.': '您每秒被动地获得 25% 的潜在工作。',
    'Calculator': '计算器',
    'Beehive': '蜂窝',
    'Antimatter Cube': '反物质立方体',
    'Acceleron': '加速器',
    'gilded points': '镀金点',
    'Acquirement Magnet': '采集磁铁',
    'Mergeables': '可合并块',
    'Upgrades': '升级',
    'More Work': '更多工作',
    'Cursor': '光标',
    'Faster Scrap Mergeables': '更快的废料可合并块',
    'Infinite Layer Cake': '无限层蛋糕',
    'Powers': '力量',
    'scrap': '废料',
    'softcapped': '软上限',
    'Summon a Treasure': '召唤宝藏',
    'Replication Galaxy': '复制星系',
    'The Button': '按钮',
    'Time Shard': '时间碎片',
    'Treasures': '宝藏',
    'The last treasure rolled is Cursor.': '最后抽取的宝藏是光标。',
    'grimoires': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Even More Mergeables": "更多可合并块",
    "Even More Work": "更多工作",
    "Your best merge tokens is ": "你的最佳合并令牌数量是",
    "Your best Mergeable Score is ": "你最好的可合并分数是",
    "Your best scrap is ": "你最佳的废料数量是",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "Mergeable Score": "可合并分数",
    " merges": " 合并",
    " to next Scrap Mergeable": " 到下一个废料合并",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^Tier ([\d\.,]+)$/, '层 $1'],
    [/^You are gaining (.+) work per second$/, '你每秒获得 $1 工作'],
    [/^Cost: (.+) work\n(.+)Level: (.+)\/(.+)\n(.+)Adds (.+) mergeables.$/, '成本：$1 工作\n 级别：$3\/$4\n 添加 $5 个可合并块。'],
    [/^Your mergers are multiplying points by (.+).$/, '您的合并将点数乘以 $1。'],
    [/^Cost: (.+) work\n(.+)Level: (.+)\/(.+)\n(.+)Increases the beginning tier of Mergeables by (.+), but multiplies Mergeable cost by (.+)$/, '成本：$1 工作\ n等级：$3\/$4 \ n增加了$6 可合并初始层，但乘以 $7 可合并成本'],
    [/^Your merge levels are providing a (.+)x multiplier to gilded points, and a (.+)x multiplier to work.$/, '您的合并等级为镀金点提供了 $1 倍的乘数，并为工作提供了 $2 倍的乘数。'],
    [/^Cost: (.+) merge tokens\n(.+)Level: (.+)\/(.+)\n(.+)Multiplies Auto-Merge speed by (.+)x. \(\+(.+)x speed additively$/, '成本：$1 合并令牌\n 等级：$3\/$4\n 自动合并速度乘以 $6 倍。 \(\+$7x 速度加成'],
    [/^Cost: (.+) merge tokens\n(.+)Level: (.+)\/(.+)\n(.+)Multiplies Merge Token gain by (.+)x. \(Base effect (.+)x$/, '成本：$1 合并令牌\n 等级：$3\/$4\n 合并令牌收益乘以 $6 倍。 \(基础效果 $7x'],
    [/^Cost: (.+) merge tokens\n(.+)Level: (.+)\/(.+)\n(.+)Multiplies Work gain by (.+). \(Basic effect (.+).$/, '成本：$1 合并令牌\n 等级：$3\/$4\n 工作收益乘以 $6。 \(基础效果 $7.'],
    [/^Cost: (.+) merge tokens\n(.+)Level: (.+)\/(.+)\n(.+)Multiplies Gilded Point gain by (.+). \(Basic effect (.+).$/, '成本：$1 合并令牌\n 等级：$3\/$4\n 镀金点收益乘以 $6。 \(基础效果 $7.'],
    [/^Cost: (.+) merge tokens\n(.+)Level: (.+)\/(.+)\n(.+)Multiplies Point gain by (.+). \(Basic effect (.+).$/, '成本：$1 合并令牌\n 等级：$3\/$4\n 点收益乘以 $6。 \(基础效果 $7.'],
    [/^Cost: (.+) merge tokens\n(.+)Level: (.+)\/(.+)\n(.+)Gilded Mergeables are (.+) cheaper. \(Base effect (.+).$/, '成本：$1 合并令牌\n 等级：$3\/$4\n 已镀金可合并块便宜 $6。 \(基础效果 $7.'],
    [/^Cost: (.+) merge tokens\n(.+)Level: (.+)\/(.+)\n(.+)Gilded Mergeables are (.+)x cheaper. \(Base effect (.+)x$/, '成本：$1 合并令牌\n 等级：$3\/$4\n 镀金 可合并块 便宜 $6x。。 \(基础效果 $7x'],
    [/^Cost: (.+) merge tokens\n(.+)Level: (.+)\/(.+)\n(.+)Adds (.+) to the More Mergeables cap..$/, '成本：$1 合并令牌\n 等级：$3\/$4\n将更多可合并上限增加 $6..'],
    [/^Cost: (.+) gilded points\n(.+)Level: (.+)\/(.+)\n(.+)Raises the gain of Work to (.+).$/, '成本：$1 镀金点\n 等级：$3\/$4\n将工作增益提高到 $6.'],
    [/^Cost: (.+) gilded points\n(.+)Level: (.+)\/(.+)\n(.+)Multiplies Point gain by (.+).$/, '成本：$1 镀金点\n 等级：$3\/$4\n将点数增益乘以 $6.'],
    [/^Cost: (.+) gilded points\n(.+)Level: (.+)\/(.+)\n(.+)Auto-merge is (.+) faster.$/, '成本：$1 镀金点\n 等级：$3\/$4\n自动合并速度提高 $6 倍.'],
    [/^Cost: (.+) gilded points\n(.+)Level: (.+)\/(.+)\n(.+)Increase the cap of More Mergeables by \+(.+).$/, '成本：$1 镀金点\n 等级：$3\/$4\n将 更多可合并块 的上限增加 \+$6.'],
    [/^Cost: (.+) scrap\n(.+)Level: (.+)\/(.+)\n(.+)Raises the gain of Work to (.+).$/, '成本：$1 废料\n 等级：$3\/$4\n将工作增益提高到 $6.'],
    [/^Cost: (.+) scrap\n(.+)Level: (.+)\/(.+)\n(.+)Multiplies Point gain by (.+).$/, '成本：$1 废料\n 等级：$3\/$4\n将点数增益乘以 $6.'],
    [/^Cost: (.+) scrap\n(.+)Level: (.+)\/(.+)\n(.+)Scrap Mergeables spawn (.+) faster.$/, '成本：$1 废料\n 等级：$3\/$4\n废料可合并块生产快 $6 倍。'],
    [/^Cost: (.+) scrap\n(.+)Level: (.+)\/(.+)\n(.+)Auto-merge and gilded auto-merge is (.+) faster.$/, '成本：$1 废料\n 等级：$3\/$4\n自动合并和镀金自动合并快 $6 倍。'],
    [/^Adding \+(.+) to the Better Mergeables cap.$/, '为 更好的合并 上限增加 \+$1。'],
    [/^Buy Gilded Mergeable for (.+) Gilded Points$/, '用 $1 镀金点 购买镀金可合并块'],
    [/^The next Gilded Mergeable costs (.+) gilded points.$/, '下一个镀金可合并块价格为$1镀金点。'],
    [/^You are gaining (.+) gilded points per second$/, '你每秒获得$1镀金点'],
    [/^You have ([\d\.]+)e([\d\.,]+) $/, '你有 $1e$2 '],
    [/^Your Gilded Mergeables are providing a (.+) multiplier to work. \(based on (.+) for each Gilded Mergeable.\)$/, '您的镀金可合并块 提供了一个 $1 倍的乘数来工作。 （基于每个镀金可合并块 的 $2。）'],
    [/^([\d\.]+)s \/ ([\d\.]+)s$/, '$1秒 \/ $2秒'],
    [/^Producing \+(.+) scrap each minute.$/, '每分钟产生 \+$1 废料。'],
    [/^Cost: ([\d\.,]+)$/, '成本: $1'],
    [/^You have (.+) merge levels$/, '你有 $1 合并等级'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^It has been (.+)s since you last performed a merge.$/, '自您上次执行合并以来已经过去了 $1 秒。'],
	[/^Your current and potential work is dividing your point gain by (.+).$/, '你当前和潜在的工作是将您的点数收益除以 $1。'],
	[/^Buy Mergeable for 1 Work$/, '购买可合并块花费 $1 工作'],
	[/^([\d\.]+)e(\d+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^Giving a (.+)x points boost.$/, '提供 $1x 的点数提升。'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);